version: "3.8"

services:
  cs336:
    image: huazhx/xuzhenhua_attention_train:latest
    container_name: xzhc
    restart: unless-stopped
    volumes:
      - ./data:/app/data    # 根据需求映射数据目录
    tty: true
    # 使用 sleep infinity 保持容器常驻，便于用 docker exec 进入 bash
    command: ["sleep", "infinity"]